version: '3'
services:
  mongo-server:
    image: mongo:3.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - "./db:/data/db"

  mongo-viewer:
    image: mongo-express:0.54.0
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - 8081:8081
    depends_on:
      - mongo-server

  mongo-app:
    build: .
    image: application
    depends_on:
      - mongo-server
      - mongo-viewer
    ports:
      - 8082:8080
